services:
  WARP:
    image: ghcr.io/w9315273/docker-warp-proxy:latest
    container_name: WARP
    network_mode: bridge
    ports:
      - "1080:1080/tcp"
      - "1080:1080/udp"
      - "1081:1081/tcp"
    environment:
      SOCKS5_PROXY_PORT: "1080"
      HTTP_PROXY_PORT: "1081"
      WARP_LICENSE_KEY: "${WARP_LICENSE_KEY}"
      WARP_TOKEN_URL: "${WARP_TOKEN_URL}"
    volumes:
      - ./WARP:/var/lib/cloudflare-warp
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    restart: always